// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Wallet = (function(_super) {
    __extends(Wallet, _super);

    function Wallet() {
      return Wallet.__super__.constructor.apply(this, arguments);
    }

    Wallet.prototype.initialize = function() {
      this.set('wallet', 500);
      return this.set('bet', 0);
    };

    Wallet.prototype.bet = function(amount) {
      var bet, wallet;
      bet = this.get('bet');
      wallet = this.get('wallet');
      if ((0 < amount && amount <= wallet) || (-bet <= amount && amount < 0)) {
        this.set('wallet', wallet - amount);
        return this.set('bet', bet + amount);
      }
    };

    Wallet.prototype.won = function() {
      console.log('test1');
      this.set('wallet', 2 * this.get('bet') + this.get('wallet'));
      return this.set('bet', 0);
    };

    Wallet.prototype.lost = function() {
      console.log('test2');
      return this.set('bet', 0);
    };

    Wallet.prototype.tied = function() {
      console.log('test3');
      this.set('wallet', this.get('wallet') + this.get('bet'));
      return this.set('bet', 0);
    };

    return Wallet;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=Wallet.map
