// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      var last;
      last = this.add(this.deck.pop()).last();
      if ((this.isDealer && this.dealerScore() > 21) || (this.scores()[0] > 21)) {
        this.trigger('bust', this);
      }
      return last;
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.playerScore = function() {
      var score;
      score = this.scores();
      if ((score[1] != null) && score[1] <= 21) {
        return score[1];
      } else {
        return score[0];
      }
    };

    Hand.prototype.dealerScore = function() {
      var score;
      score = this.scores();
      if ((score[1] != null) && score[1] >= 17) {
        return score[1];
      } else {
        return score[0];
      }
    };

    Hand.prototype.dealerTurn = function() {
      var _results;
      this.first().flip();
      if (this.isDealer) {
        _results = [];
        while (!(this.scores()[1] >= 17 || this.scores()[0] >= 17)) {
          _results.push(this.hit());
        }
        return _results;
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
